import type { Metadata } from "next";
import { Database, Lock, Server, Shield, Globe } from "lucide-react";
import { Section } from "@/components/Section";

export const metadata: Metadata = {
  title: "Security",
  description:
    "Bot Velocity Trust Center — data isolation, execution integrity, boundary protection, credential security, and secure-by-design philosophy.",
};

const trustCategories = [
  {
    title: "Data Isolation",
    icon: Database,
    points: [
      "Strict tenant and folder boundaries enforced at the database query layer",
      "Row-level isolation for all execution state and job metadata",
      "Folder-scoped RBAC restricting access to authorized organizational boundaries",
      "Robot-scoped permissions limiting automated workflow access",
    ],
  },
  {
    title: "Execution Integrity",
    icon: Server,
    points: [
      "Atomic job claiming using row-level locking to prevent race conditions",
      "Idempotent job submission guarantees via unique execution keys",
      "Lease expiry detection with automatic reclaim for stalled runs",
      "Hash-validated immutable package execution preventing tampering",
      "Strict contract version enforcement between orchestrator and runner",
    ],
  },
  {
    title: "External Boundary Protection",
    icon: Globe,
    points: [
      "SSRF protection in external tool gateway",
      "Archive path validation preventing directory traversal during zip extraction",
      "Schema validation enforcement on all runtime inputs",
      "Controlled external network access with auditable egress paths",
    ],
  },
  {
    title: "Credential Security",
    icon: Lock,
    points: [
      "Encrypted credential storage at rest per tenant",
      "TLS encryption for all data in transit",
      "Credential isolation scoped to tenant and folder boundaries",
      "No plaintext secrets in execution logs or trace data",
    ],
  },
  {
    title: "Secure-by-Design Philosophy",
    icon: Shield,
    points: [
      "Explicit state transitions — no implicit coordination between agents",
      "Deterministic retry authority prevents split-brain behavior",
      "Governance rules applied in the control path, not as external checks",
      "Audit records generated by default for all policy enforcement decisions",
      "Defense-in-depth approach across orchestration, execution, and storage layers",
    ],
  },
];

export default function SecurityPage() {
  return (
    <>
      <Section
        variant="light"
        title="Trust Center"
        description="Security architecture and operational controls for enterprise AI automation."
      >
        <p className="text-neutral-600 leading-relaxed max-w-3xl">
          Bot Velocity applies secure-by-design principles across every layer of the
          platform. Isolation, integrity, and governance are built into the execution
          model — not bolted on as external controls.
        </p>
      </Section>

      {trustCategories.map((category, idx) => (
        <Section
          key={category.title}
          variant={idx % 2 === 0 ? "dark" : "light"}
          title={category.title}
        >
          <div className="flex items-center gap-3 mb-6">
            <category.icon
              size={22}
              className={idx % 2 === 0 ? "text-indigo-400" : "text-indigo-600"}
            />
            <span className={`text-sm font-medium uppercase tracking-wider ${
              idx % 2 === 0 ? "text-neutral-400" : "text-neutral-500"
            }`}>
              {category.title}
            </span>
          </div>
          <ul className="grid gap-3 md:grid-cols-2">
            {category.points.map((point) => {
              const cardClass = idx % 2 === 0 ? "card-dark" : "card-light";
              const textClass = idx % 2 === 0 ? "text-neutral-200" : "text-neutral-700";
              return (
                <li key={point} className={`${cardClass} card-hover px-4 py-3 ${textClass}`}>
                  {point}
                </li>
              );
            })}
          </ul>
        </Section>
      ))}

      <section className="section-light border-t border-neutral-200">
        <div className="container-shell py-14 md:py-20">
          <p className="text-neutral-700">
            Security contact:{" "}
            <a
              href="mailto:security@botvelocity.com"
              className="text-indigo-600 hover:text-indigo-500"
            >
              security@botvelocity.com
            </a>
          </p>
        </div>
      </section>
    </>
  );
}
