import type { Metadata } from "next";
import {
  Activity,
  BarChart3,
  Database,
  GitBranch,
  Lock,
  Shield,
} from "lucide-react";
import { Section } from "@/components/Section";
import { FeatureCard } from "@/components/FeatureCard";

export const metadata: Metadata = {
  title: "Capabilities",
  description:
    "Technical capabilities of the Bot Velocity control plane — retry engine, lease enforcement, idempotency, evaluation, cost aggregation, and policy checks.",
};

const technicalSystems = [
  {
    title: "Retry Engine",
    icon: Activity,
    description:
      "Centralized retry authority with configurable backoff, maximum attempt limits, and dead-letter routing. Retries are lease-aware to prevent duplicate side effects across concurrent workers.",
  },
  {
    title: "Lease Enforcement",
    icon: GitBranch,
    description:
      "Every execution acquires a time-bounded lease before processing. Expired leases trigger automatic reclaim, preventing zombie runs and ensuring ownership is always authoritative.",
  },
  {
    title: "Idempotency Controls",
    icon: Database,
    description:
      "Job submission uses unique execution keys to guarantee at-most-once creation. Combined with hash-validated packages, the system prevents duplicate work and ensures replay safety.",
  },
  {
    title: "Evaluation Engine",
    icon: BarChart3,
    description:
      "Automated baseline comparison, regression detection, and flaky behavior identification across evaluation runs. LLM-judge scoring and CI gating thresholds enforce quality before deployment.",
  },
  {
    title: "Cost Aggregation",
    icon: Database,
    description:
      "Per-run token usage and spend attribution tracked across model and workflow boundaries. Hierarchical span tracing ties cost data to specific orchestration steps for variance analysis.",
  },
  {
    title: "Policy Checks",
    icon: Shield,
    description:
      "Runtime policies govern tool access, output handling, and escalation paths. Policy enforcement is applied in the control path with audit records generated by default.",
  },
];

const isolationDetails = [
  "Folder-scoped RBAC with strict tenant boundaries",
  "Encrypted credential storage per tenant",
  "Row-level data isolation at the query layer",
  "Robot-scoped permissions for automated workflows",
];

export default function CapabilitiesPage() {
  return (
    <>
      <Section
        variant="light"
        title="Technical Systems"
        description="The operational building blocks that make deterministic AI automation possible."
      >
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {technicalSystems.map((item) => (
            <FeatureCard key={item.title} {...item} variant="light" />
          ))}
        </div>
      </Section>

      <Section variant="dark" title="Isolation & Access Control">
        <ul className="grid gap-3 md:grid-cols-2">
          {isolationDetails.map((item) => (
            <li key={item} className="card-dark card-hover px-4 py-3 text-neutral-200">
              {item}
            </li>
          ))}
        </ul>
      </Section>
    </>
  );
}
